### ISSUE TITLE
TODO 기능

### ISSUE THREAD

**Issue by sss20young** [threeracha/Chuibbo-Android#44]
## 📝 TODO
- [ ] 1. SNS 로그인 3개 연동 (Google, Naver, Kakao)
- [ ] 2. 탭 A아이템 -> B아이템 클릭시, B아이템의 기존에 유지하던 fragment 제공
- [ ] 3. 탭 A아이템 -> A아이템 클릭시, A아이템 처음 클릭할 때 보여주는 fragment 제공
