### ISSUE TITLE
TODO UI 수정

### ISSUE THREAD

**Issue by sss20young** [threeracha/Chuibbo-Android#45]
## 📝 TODO
- [ ] 1. 검색어 힌트, 드롭박스 UI 변경
- [ ] 2. recyclerview 위아래로 스크롤 시, 옅은 파란색 나타나는 것 제거
- [ ] 3. 토스처럼 EditText에 정보 입력시, EditText의 힌트 -> 상단의 TextView로 이동
